### ISSUE TITLE
Validate optional and conditional fields where an explicit null is used as a value

### ISSUE THREAD

**Issue by da-banking** [ConsumerDataStandardsAustralia/dsb-schema-tools#1]
### Hypothesis
Validate optional and conditional fields where an explicit null is used as a value.

### Description
These schemas do not validate optional and conditional fields where an explicit null is used as a value, as is normally allowed by Payload Conventions ( https://consumerdatastandardsaustralia.github.io/standards/#mandatory-optional-fields )
- Optional fields MAY be present but this is not guaranteed. It is also valid for these fields to be present but have a null value
- If the conditional statement is false then the field is considered optional.

### Available Options
e.g. LinksPaginated should allow this (currently, it doesn't):
> {
>   "self": https://data.holder.com.au/cds-au/v1/banking/accounts?page=1&page-size=5,
>   "first": null,
>   "prev": null,
>   "next": https://data.holder.com.au/cds-au/v1/banking/accounts?page=2&page-size=5,
>   "last": https://data.holder.com.au/cds-au/v1/banking/accounts?page=3&page-size=5
> }

**Comment by tom-schier** [comment]
@da-banking Your interpretation seems valid. We will endeavour to create such a test.

**Comment by tom-schier** [comment]
@da-banking I have updated the schema files to reflect the optional and conditional field validation.
